export interface User {
    id: number,
    email: string,
    fullName?: string,
    avatarUrl?: string,
    phoneNumber: string,
    preferenceType?: string,
    preferenceHealthcare?: string,
    preferenceSafety? : string,
    preferenceEducation?: string,
    preferenceShopping?: string,
    preferenceTransportation?: string,
    preferenceEnvironment?: string,
    preferenceEntertainment?: string,
    liveAddress?: string,
}